#!/bin/bash
############################################################################
#
# NAME ppt2md - convert a list of files from pptx to md
#
  USAGE="ppt2md <indir> <outdir>" 
#
############################################################################

if [ $# -lt 2 ] ; then
  echo "Missing arguments. USAGE $USAGE"
  exit
fi

indir="$1"
outdir="$2"
shift 2
mkdir -p $outdir

du -a $indir | grep pptx | while read sz fle ; do # grep gets rid of folders 
  out="${fle/.pptx}"
  out="${out/.pptm}"
  out="${out##$indir}"
  echo "   converting $fle to $out.md"
  pptx2md "$fle" -o "$outdir/$out.md" -i "$outdir/images" --disable-color
done
